### ISSUE TITLE
Error with package from MS Access (timestamp)

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/dbptk-developer#422]
Description:  Caused by: org.postgresql.util.PSQLException: ERROR: column "Datum_izdaje" is of type timestamp without time zone but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.

1.  import a SIARD file from MS Access
java -Xmx1000m -Dfile.encoding=UTF-8 -jar dbptk-app-2.6.4.jar  migrate -i microsoft-access -if smucarji_2010.mdb -e siard-2 -ef out_prs.siard
2.  see dbptk-app.log_IMPORT.txt
3. load into PostgreSQL
4. see dbptk-app.log.txt

[dbptk-app.log_IMPORT.txt](https://github.com/keeps/db-preservation-toolkit/files/3915729/dbptk-app.log_IMPORT.txt)
[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/3915731/dbptk-app.log.txt)

**Comment by BorisDomajnko** [comment]
Is it possible to get v2.6.5-RC jar file to test the fix?

**Comment by hmiguim** [comment]
I'll release today a RC for you to test the fix

**Comment by BorisDomajnko** [comment]
Hello, 
another error (or same), but other column,  2.6.5-RC
[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/4128241/dbptk-app.log.txt)
[dbptk-app.logEXPORT.txt](https://github.com/keeps/db-preservation-toolkit/files/4128243/dbptk-app.logEXPORT.txt)

 The column has values like these:

DATUM_VPISA
         19.07.2019
         12.08.2019
         23.05.2019

In other date column (DATUM_SPREMEMBE) there are from time to time also longer cases like "2.06.2016 22:15:32", but I cannot see them in this column (but it is very large).
The error is:
ERROR: column "DATUM_VPISA" is of type timestamp without time zone but expression is of type character varying

**Comment by BorisDomajnko** [comment]
Closed with dbptk-app-2.9.3.jar
