### ISSUE TITLE
creating siard - queryOriginal missing from the views of Oracle and Sybase

### ISSUE THREAD

**Issue by Laurira** [keeps/dbptk-developer#451]
When creating siard file from sakila (MySql database) then the queryOriginal is nicely filled for every view.
![image](https://user-images.githubusercontent.com/3479156/82806657-e7386980-9e8e-11ea-93bf-924acf155a8e.png)

But for the databases Oracle and SyBase there is no such element created.
![image](https://user-images.githubusercontent.com/3479156/82806568-bf490600-9e8e-11ea-846f-99e6cddf0073.png)

**Comment by Laurira** [comment]
queryOriginal missing for Postgresql as well.

**Comment by hmiguim** [comment]
Close at 2a38573
