### ISSUE TITLE
Number column in Oracle with no length specified gives error in extraction of table definition 

### ISSUE THREAD

**Issue by torbenholm** [keeps/dbptk-developer#454]
Description: When using Oracle database and having a NUMBER column without length the column is "translated" to  NUMERIC(0). This causes an error in the  "extraction". Should there not be defined any length the max length is 38.

Steps required to reproduce the bug:

1. Login to Oracle and create table
   CREATE TABLE T1 (ID NUMBER);
2. 
  Run dkptk-app-2.9.0 with relevant parameters
3. Check log

Attach the dbptk-app.log.txt file below.
[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/4785083/dbptk-app.log.txt)

**Comment by thierryrama** [comment]
Thank you for fixing this that quickly. Looking forward for the next release to test it. I am having trouble to build due to being behind corporate firewall and that some dependencies are not on maven central.

I undersand the approach to default to 38 when the column size of a numeric type is 0. Oracle should have done that with the metadata but they decided to return 0 instead when no precision has been set on `NUMBER`.
```sql
               DECODE(
                   t.data_precision,
                   null,
                   DECODE(
                       t.data_type,
                       'NUMBER',
                       DECODE(t.data_scale, null, 0, 38),
                       DECODE(
                           t.data_type,
                           'CHAR',
                           t.char_length,
                           'VARCHAR',
                           t.char_length,
                           'VARCHAR2',
                           t.char_length,
                           'NVARCHAR2',
                           t.char_length,
                           'NCHAR',
                           t.char_length,
                           'NUMBER',
                           0,
                           t.data_length
                        )
                    ),
                   t.data_precision
                ) AS column_size,

```

**Comment by hmiguim** [comment]
You may need to do more steps to build by our own.

Follow this:

https://github.com/keeps/db-preservation-toolkit/blob/mguimaraes-dev/DEV_NOTES.md#building-common-parts-that-may-be-used-by-other-projects

https://github.com/keeps/db-preservation-toolkit/blob/mguimaraes-dev/DEV_NOTES.md#updating-the-dbptk-bindings-package

**Comment by torbenholm** [comment]
Thanks for a quick response

**Comment by thierryrama** [comment]
I have tested the fix on the same Oracle schema that failed earlier and I can now export. Thank you.
