### ISSUE TITLE
Validation fails when the validator runs in parallel

### ISSUE THREAD

**Issue by 006627** [keeps/dbptk-developer#458]
To validate the references between the primary key and the foreign key, a static list of SQL types is created which is cleared at the end of the process leading to another validation to the error

Steps required to reproduce the bug:

This behavior occurs in the dbptk-ui but the problem is in the dbptk-developer

1 - install cpulimit package 

2 - run the command
```
$ cpulimit -l 50 -f -- java -Xmx512M -jar target/dbvtk-2.5.1.war
```
3 - Start the validation process for two databases at the same time

**Comment by hmiguim** [comment]
Closed #458 via dcc816e.
