### ISSUE TITLE
github wiki pages contain old and useless information

### ISSUE THREAD

**Issue by Laurira** [keeps/dbptk-developer#460]
For example you have created a page "Import Config Module" but this is not in sync with previous wiki pages. If we have import config module specified what should user do with the External LOBs Filter Module? Can I specify information for External LOBs Filter Module in the Import Config Module?

Or why is there still "List Tables Module" when now user can only use Import Config Module where all the tables should be listed.

It is all very confusing. Also the help manual of the dbpkt developer itself also can not answer those questions.

**Comment by hmiguim** [comment]
Hi Lauri,

Wiki pages are updated now. External LOBs Filter Module has its own wiki page with a lot of information and references available. I also added to import config module wiki page some information about how to configure the SSH connection via parameters that was missing. 

The application usage wiki page will be analyzed and reformulated in due time.
