### ISSUE TITLE
Problem with exporting GIS data with Datatype ST_GEOMETRY

### ISSUE THREAD

**Issue by BDKLarsPetersen** [keeps/dbptk-developer#463]
Description: 

Steps required to reproduce the bug:

1. 
[ora1427.zip](https://github.com/keeps/dbptk-developer/files/5240614/ora1427.zip)

With Oracle trace I have found that the attached ora1427.
[Oracle_all_types.zip](https://github.com/keeps/dbptk-developer/files/5240631/Oracle_all_types.zip)
SQL gives the error
2. 
3. C:\dbptk>java -jar "-Dfile.encoding=UTF-8" dbptk-app-2.3.0.jar --import oracle --import-server-name=audvdb1.baneudv.dk --import-instance="qa1.baneudv.dk" --import-port-
mber=1521 --import-username=btr_statensarkiv --import-password="btr_statensarkiv" --import-accept-license --export=siard-dk --export-folder="C:\AVID.SA.20767.1"
      Converting database: oracle to siard-dk
      Initializing database
      Exporting SIARD version dk
      Obtaining table structure for BTR_STATENSARKIV.BTR_KNUDER
ERROR Fatal error while converting the database (ORA-01427: enkelt-r├ªkke underforesp├╕rgsel returnerer mere end ├⌐n r├ªkke)
      Log files and migration reports were saved in C:\dbptk
      Troubleshooting information can be found at http://www.database-preservation.com/#troubleshooting
      Please report any problems at https://github.com/keeps/db-preservation-toolkit/issues/new

I have attached som data from SYS.ALL_TYPES and there atre 2 records of ST_GEOMETRY- that caauses the error 

Attach the dbptk-app.log.txt file below.
[dbptk-app.log.txt](https://github.com/keeps/dbptk-developer/files/5240596/dbptk-app.log.txt)

Hope you can help
We have to dleiiver data to Danish State Archive of our Railnet data.

Regards
Lars Petersen
Banedanmark Infrastructure Manager
IT, Operations

**Comment by hmiguim** [comment]
Hi,

Could you please try with the latest version of DBPTK Developer (follow the [link](https://github.com/keeps/dbptk-developer/releases/latest)) and see if the error persists? 

If so, please provide the log file as you did

**Comment by BDKLarsPetersen** [comment]
Hi

Now I got a new error
[dbptk-app.log.txt](https://github.com/keeps/dbptk-developer/files/5246251/dbptk-app.log.txt)
[dbptk-report-20200918164614256.txt](https://github.com/keeps/dbptk-developer/files/5246252/dbptk-report-20200918164614256.txt)

Following command
java -jar "-Dfile.encoding=UTF-8" dbptk-app-2.9.4.jar migrate --import oracle --import-server-name=audvdb1.baneudv.dk --import-instance="qa1.baneudv.dk" --import-port-number=1521 --import-username=btr_statensarkiv --import-password="btr_statensarkiv" --import-accept-license --export=siard-dk --export-folder="C:\AVID.SA.20767.1"

Regards
Lars Petersen

**Comment by hmiguim** [comment]
Hi @BDKLarsPetersen 

DBPTK Developer only supports Oracle SDO_GEOMETRY. 

ST_GEOMETRY is converted to an unknown type which gives the error, although it should fail with a message rather than a NPE.

**Comment by BDKLarsPetersen** [comment]
Hi

Okay, but do you know hos to convert from SDE.ST_GEOMETYR to SDO_GEOMETRY ?


Regards
Lars H Petersen
Oracle developer
Banedanmark
It

Fra: Miguel Guimarães <notifications@github.com>
Sendt: 18. september 2020 17:41
Til: keeps/dbptk-developer <dbptk-developer@noreply.github.com>
Cc: Lars Helge Petersen (LHP) <lhp@BANE.dk>; Mention <mention@noreply.github.com>
Emne: Re: [keeps/dbptk-developer] Problem with exporting GIS data with Datatype ST_GEOMETRY (#463)


Hi @BDKLarsPetersen<https://github.com/BDKLarsPetersen>

DBPTK Developer only supports Oracle SDO_GEOMETRY.

ST_GEOMETRY is converted to an unknown type which gives the error, although it should fail with a message rather than a NPE.

-

**Comment by kuldaraas** [comment]
@hmiguim can confirm but I think you have to convert the values before applying DBPTK and creating the SIARD snapshot. There's not much information about the conversion on the web but maybe this link will help: https://gis.stackexchange.com/questions/187686/st-geometry-to-sdo-geometry

**Comment by hmiguim** [comment]
Closing down this issue, if any news comes up about this feel free to open a new issue or re-open this one.
