### ISSUE TITLE
Interoperability: SIARD 2.1/2.1.1 schema name empty string = valid metadata.xml

### ISSUE THREAD

**Issue by solfeggietto** [keeps/dbptk-developer#468]
Referrring to reported Issuo om DILCISBoard 2019-06-06.

https://github.com/DILCISBoard/SIARD/issues/45

The DBPTK SIARD-validator should be strict validation according to SIARD-specification - with focus on interoperability, and not narrowed to DBPTK's own implementation of the standard. An empty schema name element in a metadata.xml does successfull validate towards the metadata.xsd, furthermore the SIARD 2.1 specification tells this xml element is mandatory, but not that it cannot be empty string. It is common practice for database migration tools is to let empty schema name be interpreted as the default schema name when migrating a database from A to B. This is the way some SIARD-tools also export the SIARD-file, so when the default schema is in use in a MS SQL Server database, then the exported SIARD-file may have empty schema name string, yet the element is present and is valid xml towards xsd. And also according to the SIARD spec.

##### Details showing it is valid to be empty string shcema name #####

An interoperability question to SIARD 2.1/2.1.1 schema name empty string.

5.2 Schema level metadata (metadata.xml)
name | Schema name in the database | M = Mandatory

Example with schema name element included, but with empty string value:
[schema></name]

====>>> Replaced starting < with [ and end > with ] to display proper here:

?xml version="1.0" encoding="utf-8"?>
siardArchive xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bar.admin.ch/xmlns/siard/2/metadata.xsd metadata.xsd" version="2.1" xmlns="http://www.bar.admin.ch/xmlns/siard/2/metadata.xsd">
!--Total tables: 163-->
!--Total rows: 1 852 840-->
.......[dbname>
..........[schemas>
................[schema>
.....................[name></name]
.....................[folder>schema0</folder]
.....................[tables]
............................[table]
..................................[name>antall_poster</name]
..................................[folder>table0</folder]
..................................[!--path: schema0/table0--]
..................................[columns]
..........................................[column]
................................................[name>aar</name]
................................................[type>INT</type]
................................................[typeOriginal>INT</typeOriginal]
................................................[nullable>true</nullable]
..........................................[column]

This metadata.xml validates towards metadata.xsd
This metadata.xml is according to PDF spec as the mandatory element name is present.

There are no written spec that a mandatory element cannot be empty string "".

Microsoft SQL server use the term "default" schema, so a database migration tool may read a database using default schema as the schema name being "". Thus when migration this database to another SQL server wich may have another "default" shcema, the migration will simply use that other default schema and the system is successfullt migrated.

This is a good example of an interoperability issue, as different SIARD tool vendors may interpret this differently, where one may allow and encourage the empty "" schema name for handling the default schema case, another SIARD tool vendor may dissaly empty shcema names.

So the SIARD spec should state either that empty schema name is allowed or not.
And the same goes for all other mandadory XML element or attributes in metadata.xml or table[n].xml for the data.

My main point is that if possible, the metadata.xsd should target such cases, making metadata.xml fail to validate towards metadta.xsd if any case of disallowed metadata.xml element or attribute occur. This will make interoperability unquestionable in such cases

**Comment by luis100** [comment]
DBPTK SIARD validator validates against the specification which states the schema name is mandatory. Being mandatory but empty does not make sense on our view. Although the specification could be more clear if mandatory field can be empty, as a general rule of thumb, we consider that they cannot.

Another example of this situation is the table name, which is mandatory in the specification but the XML schema allows it to be empty. It is clear that the spirit of the specification is to mandate it to be a non-empty string, even if this is not validated in the official XML schema.

This is our interpretation of the current SIARD specification, if in a new version this is made more clear we can change the behaviour. Until then, we that this is the most correct interpretation.

**Comment by solfeggietto** [comment]
I do hope DILCISBoard or others who rule the SIARD spec will clearify this matter, so all software vendors may implement for Interoperabilty in mind.

As for the schema name versus table name, their properties are so different that its not direct comparable (theres ONE schema name in most cases of preserving one system, while the table names are always a large number. And where we can be fine using empty string for schema name (meaning default schema), an empty string for table names makes no sense.

So your point of view and SIARD spec interpretation is one way to look at it, just like the possibility of using empty string schema names as default schemas.

**Comment by luis100** [comment]
The concept of "default schema" is not supported or identifiable on the generality of database management systems nor is something defined in the SIARD specification. You are taking a particular case and making it the general case, where another approach is to map the particular case into the general case by giving a name to a schema for DBMS that have the concept of "default schema".

So, I would not vote for introducing the concept of "default schema" in SIARD specification, but would certainly prefer that the specification is clear on how it stands on the this and what should be the expected behaviour when a DBMS does not support multiple schemas and/or has a default schema without any explicitely defined name.

Furthermore, I would certainly prefer for the SIARD specification and official XML metadata schema to be very clear on what they mean by mandatory fields and if they can be an empty string, and what does the "empty string" mean in every place it is allowed.
