### ISSUE TITLE
MS Access unexpected NPE

### ISSUE THREAD

**Issue by hmiguim** [keeps/dbptk-developer#470]
Relate to: https://github.com/keeps/dbptk-ui/issues/250

> Description:
> We go nullpointer exception when trying to create a siardfile and we cannot sea any glues in the logfile, below is all notes:
> 
> 2020-10-02 14:09:16,334 [http-nio-auto-1-exec-9] INFO c.d.m.m.i.MsAccessUCanAccessImportModule - Obtaining table structure for PUBLIC.tblPlocklista
> 2020-10-02 14:09:17,264 [http-nio-auto-1-exec-4] ERROR c.d.c.c.c.utils.AsyncCallbackUtils - [0:0:0:0:0:0:0:1] AsyncCallback error - RESTException: Remote exception caused by GenericException: Could not create the SIARD file caused by NullPointerException:
> 
> we are using the latest desktop client, dbptk-desktop-2.5.3.exe.
> 
> Any ideas?

**Comment by hmiguim** [comment]
@martenlindstrandx could you try to run the export with DBPTK Developer to see if the logs provide more information?

**Comment by martenlindstrandx** [comment]
Hello Miguel,

Developer version is  working fine, we will use this one as standardclient from nöjd ;-)

/Mårten

Hämta Outlook för Android<https://aka.ms/ghei36>

________________________________
