### ISSUE TITLE
Oracle connection fails if password has special characters

### ISSUE THREAD

**Issue by Exasis** [keeps/dbptk-developer#471]
Description:
When trying to connect to an oracle database using the latest verison of the CLI tool (v. 2.9.5), the connectionstring generated for the jdbc driver is invalid. It generates two slashes in front of the server name which invalidates the URL

Steps required to reproduce the bug:

1. Try to export using the oracle import-module
2. See dbptk-app.log.txt that jdbc connectionstring includes two slashes before the servername

Attach the dbptk-app.log.txt file below.
[dbptk-app.log.txt](https://github.com/keeps/dbptk-developer/files/5376063/dbptk-app.log.txt)

**Comment by luis100** [comment]
@Exasis does your database password have special characters?

@hmiguim note that username and password are being passed in the connection string but they should be passed as connection properties to avoid having problems with special characters.

https://github.com/keeps/dbptk-developer/blob/master/dbptk-modules/dbptk-module-oracle/src/main/java/com/databasepreservation/modules/oracle/in/Oracle12cJDBCImportModule.java#L86

https://stackoverflow.com/a/21909047

**Comment by Exasis** [comment]
@luis100 it has a dash in it, so i guess that it does. I see now that you are right this is the issue, it works if i change the password. I am sorry, i was thrown off by the prefixed dashes on the connection.

**Comment by hmiguim** [comment]
Add this fix to the other database connection as well

**Comment by hmiguim** [comment]
Fixed at 24c57a7707f597222c6f9160de6954ee049c4556
