### ISSUE TITLE
'numeric' column type without any precision or scale is assumed to be integer

### ISSUE THREAD

**Issue by hmiguim** [keeps/dbptk-developer#477]
From the docs:

> Specifying NUMERIC without any precision or scale creates a column in which numeric values of any precision and scale can be stored, up to the implementation limit on precision.

https://www.postgresql.org/docs/9.3/static/datatype-numeric.html

In order to solve this, DBPTK when convert NUMERIC data type without precision and scale should assign a precision and a scale to the data type.

**Comment by PhillipTommerholt** [comment]
With fixes like this - is there a test to make sure that non-functional requirements such as conversion time is not growing rapidly?
