### ISSUE TITLE
Problem with overwriting existing folder when exporting to SIARD-DK

### ISSUE THREAD

**Issue by T33py** [keeps/dbptk-developer#480]
Description: 
When running the following command:
`java "-Dfile.encoding=UTF-8" -jar  dbptk-app-2.9.7.jar migrate -i "microsoft-sql-server" -is "DB" -idb "ArkiveringsTestDatabase" -iu "dbptk" -ip "pwd123" -ide -il -e "siard-dk" -ef "D:\Projekter\projekt\DBPTK\tst2\AVID.SA.12223.1"`

with the folder `'D:\Projekter\projekt\DBPTK\tst2\AVID.SA.12223.1'` present on the disk the program produces this output:

`Converting database: microsoft-sql-server to siard-dk
      Initializing database
      Exporting SIARD version dk
ERROR Fatal error while converting the database (Error deleting existing directory)
      Log files and migration reports were saved in D:\Pojekter\Jammerbugt\DBPTK\Program
      Troubleshooting information can be found at https://github.com/keeps/dbptk-developer/wiki/Troubleshooting
      Please report any problems at https://github.com/keeps/dbptk-developer/issues/new`

This was not resolved by running in admin mode for some reason, and the issue is quite severe in the gui version, since you can't target folders that doesn't exist there.

The exception is thrown from the file `dbptk-developer\dbptk-modules\dbptk-module-siard\src\main\java\com\databasepreservation\modules\siard\out\output\SIARDDKDatabaseExportModule.java` between lines 68 and 75. This is also shown in the log.

Steps required to reproduce the bug:

1. Create target folder (empty)
2. Run dbptk-app-2.9.7.jar with the newly created target folder and SIARD-DK as the chosen output

[dbptk-app.log.txt](https://github.com/keeps/dbptk-developer/files/6278815/dbptk-app.log.txt)

Attach the dbptk-app.log.txt file below.

**Comment by T33py** [comment]
I should probably have mentioned that I ran the program on windows.

Also I would suspect that the call `basicFileAttributes.creationTime().toString();` at line 71 may result in an invalid foldername.

**Comment by hmiguim** [comment]
@T33py in the next days I shall look into this bug and report with a possible solution

**Comment by aatrisgn** [comment]
I am experiencing the same issue with a fresh installation of the desktop database-preservation application (On windows).

Is there any work-around for this bug by using the console application instead?

**Comment by aatrisgn** [comment]
It seems like there is a work-around for this initial problem for the desktop application. If you create a given folder, choose it via the desktop application and delete the folder after creation, the application can continue.

**Comment by T33py** [comment]
> I am experiencing the same issue with a fresh installation of the desktop database-preservation application (On windows).
> 
> Is there any work-around for this bug by using the console application instead?

The console application does not have this bug. It seems to be a difference in the setup before calling the library used by both.
