### ISSUE TITLE
This parser does not support specification "dbptk-core" version "2.9.8"

### ISSUE THREAD

**Issue by tohol42** [keeps/dbptk-developer#486]
Trying to run dbptk 2.9.8 but getting the error: This parser does not support specification "dbptk-core" version "2.9.8"

This is the CLI I am running (Environment variables set accordingly)

java -jar "-Dfile.encoding=UTF-8" %APP_HOME%\dbptk-app-2.9.8.jar migrate --import=import-config --import-file=eksporSVSA.yaml --export=siard-dk --export-archiveIndex=archiveIndex\archiveIndex.xml --export-contextDocumentationIndex=contextDocumentationIndex\contextdocumentationIndex.xml --export-contextDocumentationFolder=contextDocumentationFolder --export-folder=%AV%

Any comments?
Logfile attached
[dbptk-app.log-1.txt](https://github.com/keeps/dbptk-developer/files/6740176/dbptk-app.log-1.txt)

**Comment by luis100** [comment]
Fix released on https://github.com/keeps/dbptk-developer/releases/tag/v2.9.9

**Comment by tohol42** [comment]
Thanks for quick response fix release :)
