### ISSUE TITLE
Problems with v2.9.7 

### ISSUE THREAD

**Issue by BDKLarsPetersen** [keeps/dbptk-developer#487]
Description: 

Steps required to reproduce the bug:

1. Extract Oracle table with a SDE.ST_GEOMETRY in
2. CREATE TABLE BTR_STATENSARKIV.BTR_KNUDER
(
  OBJECTID        INTEGER                       NOT NULL,
  KNUDEID         NUMBER(10)                        NULL,
  STRKAFS         NUMBER(10)                        NULL,
  SPORNUMMER      NVARCHAR2(50)                     NULL,
  KM              NUMBER(8,3)                       NULL,
  BEMAERKNING     NVARCHAR2(100)                    NULL,
  SPORTYPETEKST   NVARCHAR2(100)                    NULL,
  KNUDETYPETEKST  NVARCHAR2(100)                    NULL,
  STRKAFS_NAVN    NVARCHAR2(100)                    NULL,
  STRKAFS_FORK    NVARCHAR2(50)                     NULL,
  WGS_X           NUMBER(38,8)                      NULL,
  WGS_Y           NUMBER(38,8)                      NULL,
  UTM_X           NUMBER(38,8)                      NULL,
  UTM_Y           NUMBER(38,8)                      NULL,
  SHAPE           SDE.ST_GEOMETRY                   NULL,
  RELEASEDATO     DATE                              NULL
)
LOB ("SHAPE"."POINTS") STORE AS (
  TABLESPACE  USERS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          64K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                  FLASH_CACHE      DEFAULT
                  CELL_FLASH_CACHE DEFAULT
                 ))
TABLESPACE USERS
2. 
3. Gets error - I think it has something to do with datatypes .

SQL>select * from all_types where type_name = 'ST_GEOMETRY' gives 2 rows
OWNER TYPE_NAME TYPE_OID
--------  -------------  -----------
MDSYS	ST_GEOMETRY 4BA3494AB3EEE5B6E040578CB2057856
SDE	ST_GEOMETRY	 A618FA8DD1D84E13B35784E171530100

Can you help ?
Regards
Lars Petersen
Banedanmark, It

5. 
4. 

Attach the dbptk-app.log.txt file below.

[dbptk-app.log.txt](https://github.com/keeps/dbptk-developer/files/6791860/dbptk-app.log.txt)

**Comment by hmiguim** [comment]
Hi @BDKLarsPetersen,

DBPTK Developer only supports SDO_GEOMETRY datatype, although the NPE (NullPointer Exception) will be fixed.

**Comment by luis100** [comment]
Fix released on https://github.com/keeps/dbptk-developer/releases/tag/v2.9.9

**Comment by BDKLarsPetersen** [comment]
Thanks for your quick update:)

//Lars Petersen
Bdk
