### ISSUE TITLE
Microsoft SQL Server use integrated login on Windows

### ISSUE THREAD

**Issue by hmiguim** [keeps/dbptk-developer#488]
See https://github.com/keeps/dbptk-ui/issues/272 for more information.

Better support for windows authentication with DBPTK Developer

**Comment by luis100** [comment]
Fix released on https://github.com/keeps/dbptk-developer/releases/tag/v2.9.9

**Comment by clausjuhl** [comment]
Hi. When using the "-il" flag, I get an error telling me that Integrated Windows Login is not implemented. I'm using version 2.9.10 on a Windows 10 machine, trying to export an SQL Server database like so:

`java  "-Dfile.encoding=UTF-8" -jar dbptk-app-2.9.10.jar migrate -i microsoft-sql-server -is <servername>-idb <dbname> -iu <username> -ip <password> -il -ide -e siard-2 -ef <siard archive file>`

Am I doing something wrong? Supposedly Integrated Windows Login functionality was implemented in version 2.9.9.

Thank you for an excellent tool!
