### ISSUE TITLE
export external lobs (--eel) exports regular non-external LOBs as well

### ISSUE THREAD

**Issue by Laurira** [keeps/dbptk-developer#501]
Usually external lobs are big files and it is reasonable to export those files outside from siard and therefor DBPTK has the --eel parameter. Problem is that when using this parameter then all the internal small lobs will be exported outside the siard as well. For example if user has bigger text fields in the database then these should remain in the siard otherwise there will be millions of small files.

The best fix in our opinion could be that you add a feature where you can specify how big LOBs will be exported outside from siard.

**Comment by hmiguim** [comment]
marked as duplicated from #504
