### ISSUE TITLE
dbptk can not take along external LOBs that include spaces in file names

### ISSUE THREAD

**Issue by Laurira** [keeps/dbptk-developer#503]
For example file with name "Kommentaar metsaseire andmete juurde.docx" is not added into lobseq folder along siard file and the validator gives the error as well. Other files without spaces in names are nicely in their correct place.

**Comment by Laurira** [comment]
seems like that issue were related to estonian special characters ä, ü, ö, õ that can be bypassed when executing jar file with "java -Xmx5g "-Ddbptk.jdbc.fetchsize.default=10000" "-Dfile.encoding=UTF-8" "-Dsun.jnu.encoding=UTF-8"

**Comment by luis100** [comment]
@hmiguim please check if the work-around for this issue is available on the documentation.
