### ISSUE TITLE
SIARD Validation does not understand zip-internal LOB files.

### ISSUE THREAD

**Issue by stighemmer** [keeps/dbptk-developer#560]
A SIARD file can store data in three ways:
- By default, in the "tableNNN.xml" file.
- As external LOB files, outside the SIARD
- As internal LOB files, inside the SIARD, but visible with ZIP tools.

dbptk migrate can only produce the first two, which is fine. No complaint there.  
dbptk validate will only recognize the first two.  This is NOT fine.  Other programs produce SIARD files that are valid according to the standard, but which dbptk complain about.

Steps required to reproduce the bug:

0. (Running Windows 10 Pro 22H2  and java openjdk 17.0.8.1 2023-08-22 LTS)

1.  Download the attached ZIP file and rename to SIARD
2. java "-Dfile.encoding=UTF-8" --add-opens java.xml/com.sun.org.apache.xerces.internal.jaxp=ALL-UNNAMED -cp "dbptk-app-2.10.4.jar;jaxb-api-2.3.1.jar" com.databasepreservation.Main validate -if TestDB-lob.siard
3. Read the Error messages in attached validation report.

The command line is convoluted because of another issue.  Not relevant here.

There are two error messages:

P_4.2-3: [ERROR] - The individual table folders contain an XML file and an XSD file, the names of
which (folder designation and both file names) must be identical. - content\schema0\table0\lob1\seg0\rec1.txt
Structure of the SIARD archive file [FAILED]

Here the validator complains about extra files in the SIARD file.

A_M_5.6-1-2: [ERROR] : not found external lob 'seg0/rec1.txt' required by 'content/schema0/table0 [row: 1 column: c1]'

Here the validator complain it cannot find the file it just complained about finding.

Two spurious error messages might not seem like a big deal, but when our database contains a million LOBs, we get two million error messages.  Sorting out any actual errors become difficult.

[testdb-lob.zip](https://github.com/keeps/dbptk-developer/files/12452556/testdb-lob.zip)
[dbptk-validation-reporter-TestDB-lob-20230828103622012.txt](https://github.com/keeps/dbptk-developer/files/12452564/dbptk-validation-reporter-TestDB-lob-20230828103622012.txt)
[dbptk-app.log.txt](https://github.com/keeps/dbptk-developer/files/12452609/dbptk-app.log.txt)

**Comment by AntonioG70** [comment]
Hi, 

On the SIARD 2.1 specification, segments are not available inside lob folders, thats why you get the P_4.2-3 error. To fix it, you have to store the record directly inside the lob1 folder. 

About the A_M_5.6-1-2 error, a fix will be developed to fix this because it should not happen.

**Comment by stighemmer** [comment]
I created a file with no segments.  Both errors are still given.

[testdb-lob-2.zip](https://github.com/keeps/dbptk-developer/files/14191323/testdb-lob-2.zip)
[dbptk-validation-reporter-TestDB-lob-2-20240207100133905.txt](https://github.com/keeps/dbptk-developer/files/14191328/dbptk-validation-reporter-TestDB-lob-2-20240207100133905.txt)
[dbptk-app.log.txt](https://github.com/keeps/dbptk-developer/files/14191329/dbptk-app.log.txt)

**Comment by AntonioG70** [comment]
Hi,
The SIARD 2.1 specification also says it is advisable to normalize the lob folders and lob files and to use, for example,
lob1/ and record0.bin, record0.txt, or record0.xml instead of the actual name, or a file extension associated with the MIME type of the lob files in case this is known. To pass the P_4.2-3 validation you have to change your record name to record1.txt (it is rec1.txt).

About the A_M_5.6-1-2 error, the fix for this was not yet deployed so you will still get this error.

**Comment by stighemmer** [comment]
Can confirm that the suggested fix solves the first error message.

HOWEVER, I think the validator is too strict here.  Shall we continue that discussion here or should I open another issue?

**Comment by AntonioG70** [comment]
I think it would be better to open another issue in order to discuss that matter.
