### ISSUE TITLE
The program doesn't recognize --import-database also -idb

### ISSUE THREAD

**Issue by MJozsefVR** [keeps/dbptk-developer#563]
Description: I would like to connect to an oracle database to export SIARD 2. The program doesn't seem to recognize the --import-database while connecting to Oracle. I would like to connect to an oracle database to export SIARD 2.

Steps required to reproduce the bug:

1.  java -jar "-Dfile.encoding=UTF-8" dbptk-app-2.10.2.jar migrate --import oracle --import-server-name=ora-scan.natarch.hu --import-database=seshat.natarch.hu --import-username=**** --import-password=**** --import-port-number=1521 --import-accept-license --export siard-2 --export-file=example.siard

ERROR Unrecognized option: --import-database=seshat.natarch.hu

Attach the dbptk-app.log.txt file below.
[dbptk-app.log.txt](https://github.com/keeps/dbptk-developer/files/12838068/dbptk-app.log.txt)

**Comment by stighemmer** [comment]
Import module: -i oracle, --import=oracle
            -is, --import-server-name=value
                  (required) the name (or IP address) of the Oracle server
            -ii, --import-instance=value
                  (required) the name of the instance to use in the connection
            -iu, --import-username=value
                  (required) the name of the user to use in connection
            -ip, --import-password=value
                  (required) the password of the user to use in connection
            -ipn, --import-port-number=value
                  (required) the server port number
            -ial, --import-accept-license
                  (optional) declare that you accept OTN License Agreement, which is necessary to
                  use this module
            -issh, --import-ssh
                  (optional) use to perform a SSH remote connection
            -ish, --import-ssh-host=value
                  (optional) the hostname of the remote server
            -isu, --import-ssh-user=value
                  (optional) the name of the remote user to use in the SSH connection
            -ispw, --import-ssh-password=value
                  (optional) the password of the remote user to use in the SSH connection
            -ispn, --import-ssh-port=value
                  (optional) the port number remote server is listening

The oracle module does not recognize the -idb option at all.

This is because the way Oracle organizes things, host and port uniquely determines the database, so it need not be specified.

**Comment by MJozsefVR** [comment]
Thank you for clearing this up
The [Oracle to SIARD 2 example](https://github.com/keeps/dbptk-developer#examples)  and the [application usage ](https://github.com/keeps/dbptk-developer/wiki/Application-usage) examples however did contain the import database value: java -jar "-Dfile.encoding=UTF-8" dbptk-app-x.y.z.jar migrate --import oracle --import-server-name=127.0.0.1 --import-database="example_db" --import-username=username --import-password="p4ssw0rd" --import-accept-license --export siard-2 --export-file=example.siard

**Comment by hmiguim** [comment]
Thanks for noticing it, I'll update the documentation to fix this inconsistency,
