### ISSUE TITLE
Build of default profile without Java 8 is broken

### ISSUE THREAD

**Issue by daniel-skovenborg** [keeps/dbptk-developer#605]
Because `dbptk-bindings` has been added to the default Maven profile it can no longer be build with a Java version newer than Java 8. The build fails with:
```
[ERROR] Failed to execute goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.3:generate (generate-jaxb-siard) on project dbptk-bindings-siard1: Execution generate-jaxb-siard of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.3:generate failed: A required class was missing while executing org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.3:generate: com/sun/codemodel/CodeWriter
```

The `dbptk-bindings` module should be removed from the default profile again, or `DEV_NOTES.md` should instruct to install JDK 1.8 and set `JAVA_HOME`.
On Ubuntu:
```
$ sudo apt install openjdk-8-jdk
$ JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 mvn -Dmaven.test.skip clean package
```

**Comment by luis100** [comment]
Instead, dbptk-binding should be made compatible with Java 9+ even if dropping compatibility with Java 8.

**Comment by daniel-skovenborg** [comment]
I agree, I just felt that was too much to ask :-)

**Comment by daniel-skovenborg** [comment]
I can confirm that the issue is solved. Sorry if I interrupted your workflow by clicking the Close button, I should probably have just commented instead.
